server:
  port: 8888
spring:
  application:
    name: spring-config-server
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 5

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_URL:localhost:8090}/realms/myrealm/protocol/openid-connect/certs

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  endpoints:
    health:
      probes:
        enabled: true
      rabbit:
        enabled: true
      show-details: always
    env:
      enabled: true  # Ajuste conforme necessário
    prometheus:
      enabled: true
    web:
      exposure:
        include: ["*"]
      base-path: /infra/config/actuator
  metrics:
    enable:
      jvm: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.config: INFO
    com.github.loki4j.logback: INFO
    org.springframework.security: INFO
    org.springframework.cloud.bus: INFO
