server:
  port: 8888
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          search-paths: /{application}
          clone-on-start: true
          force-pull: true
        default-label: main
    bus:
      enabled: true
    stream:
      default-binder: rabbit
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 5


logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.config: INFO
    com.github.loki4j.logback: INFO

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      rabbit:
        enabled: true
      show-details: always
    env:
      post:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /infra/config/actuator
  metrics:
    jvm: true
  prometheus:
    metrics:
      export:
        enabled: true
