server:
  port: 8888

spring:
  application:
    name: saog-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: file://home/lsilva/Dev/workspace/Leandro-Labs/spring_config_repo/
#          search-paths: /{application}
  profiles:
    active: local
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    connection-timeout: 5

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework.cloud: DEBUG
    org.springframework.cloud.config: DEBUG