spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/llsilvas/spring_config_repo.git
          search-paths: /{application}
          clone-on-start: true
          force-pull: true

